# Generated by Django 5.0.3 on 2024-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
