# Generated by Django 5.0.1 on 2024-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='bar_code',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
